##MySQL
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop_management?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
##mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: online.zsdntech.ecommercemanagementsystem.entity

